### ISSUE TITLE
Example program did't work. table.txt was required.

### ISSUE THREAD

**Issue by ssth4949** [Phuriches/OCR_RaspberryPi_edgetpu#1]
Hi, thank you for your great work! I would like to test your program, but it required table.txt. It would be grateful if you could upload the other example files to make the demo program work.

**Comment by Phuriches** [comment]
Thank you for your comment! 
Please see https://github.com/FLming/CRNN.tf2/blob/master/example/table.txt for 'table.txt' file.

**Comment by ssth4949** [comment]
Thank you for your prompt response! It worked:)
